engines:
  rubocop:
    enabled: false
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  brakeman:
   	enabled: false
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
  	enabled: true
    config:
    	languages:
      	#mass_threshold: 30
      - javascript
ratings: # customize
  paths:
  - src/**/*
exclude_paths: # customize
- .bundle/
- build
- coverage
- mochawesome-report
- node_modules
- test
- tools
- .nyc_output
