engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
    - specs
  eslint:
    enabled: true
    config: ./.eslintrc.js
    channel: 'eslint-2'
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - '**/*.js'
exclude_paths:
- .nyc_output
- coverage
- dist
- esdoc
- node_modules
- test
- tolls
- mochawesome-report
- build
- gulpfile.js
