export const VALID = 'VALID';
export const MISSING_EVIDENCE = 'MISSING_EVIDENCE';
export const INVALID_SELECTION = 'INVALID_SELECTION';
export const UNSAVED_TASK = 'UNSAVED_TASK';
export const NO_TASKS_SELECTED = 'NO_TASKS_SELECTED';